version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: sudo apt update
          command: sudo apt update
      - run:
          name: sudo apt install postgresql postgresql-contrib
          command: sudo apt install postgresql postgresql-contrib
      - run:
          name: psql --version
          command: psql --version
      - run:
          name: sudo service postgresql start 
          command: sudo service postgresql start
      - run:
          name: gem install bundle
          command: gem install bundle

