version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: sudo apt update
          command: apt update
      - run:
          name: sudo apt update
          command: apt install postgresql postgresql-contrib
      - run:
          name: check psql version
          command: psql --version
      - run:
          name: Gem install bundler
          command: gem install bundler:2.2.14
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: check postgres version
          command: psql --version
      - run:
          name: create db
          command: rails db:create
      - run:
         name: run tests
         command: rspec
      - ruby/bundle-install
